### PR TITLE
update presence.py

### PR DESCRIPTION
**Pull request by TaIFeel**
work RPC with 2 characters in small | large text

### CODE REVIEW

**Comment by LyQuid12** [comment]
As far as I know, the minimum RPC of the character is 3. Is this possible?

**Comment by TaIFeel** [comment]
No, I try with 2 character and work

**Comment by TaIFeel** [comment]
изображение

**Comment by LyQuid12** [comment]
Well okay, merge soon.

**Comment by LyQuid12** [comment]
Merged.

**Pull request merged**
